version: '3.3'

services:
  spring-app:
    image: openjdk:21
    container_name: spring-app
    volumes:
      - ./deploy-0.0.1-SNAPSHOT.jar:/app/backend.jar
    working_dir: /app
    command: ["java", "-jar", "backend.jar"]
    ports:
      - "8099:8099"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge